### PR TITLE
Update Exogains emission variable names.

### PR DESCRIPTION
**Pull request by robinhasse**
This update is necessary after REMIND reporting variables have been renamed. It has to be merged before the change in remind2 though as tests in remind2 rely on a compatible piamInterfaces version.

### CODE REVIEW

**Review by orichters — APPROVED** [review]
Thanks, that is a good idea to harmonize the names. Still, does piamInterfaces avoids that you can submit to remind2? That should not be the case, I think we wanted buildLibrary() just to issue a warning or something like that.

**Comment by robinhasse** [comment]
> Still, does piamInterfaces avoids that you can submit to remind2? That should not be the case, I think we wanted buildLibrary() just to issue a warning or something like that.

There is a new test in remind2 that `lucode2::buiildLibrary` runs that requires a piamInterfacing working with your changes in remind2. @fbenke-pik and I are currently discussing this work flow because it is a bit cumbersome.

**Comment by orichters** [comment]
Deleting [this line](https://github.com/pik-piam/remind2/blob/ec2112feb43510267b997f0b2e3891cac3305f57/tests/testthat/test-piamInterfaces.R#L33) should do it. You get a warning, but no failing.

**Comment by robinhasse** [comment]
> Deleting [this line](https://github.com/pik-piam/remind2/blob/ec2112feb43510267b997f0b2e3891cac3305f57/tests/testthat/test-piamInterfaces.R#L33) may do it. You get a warning, but no failing.

True, but I is also a good reason to have the error: You won't forget to update project mappings. Seems that @fbenke-pik and RSE in general are taking a look.

**Comment by orichters** [comment]
Checked it, doesn't work, it still fails because of the warning. I think it is sufficient to have a warning, but this should keep anyone away from committing to remind2.

**Pull request merged**
