### PR TITLE
new CAMP mapping that is based on ECEMF instead of NAVIGATE

### PR DESCRIPTION
**Pull request by jmuessel**
Note that the Tier column was part in the ARIADNE template but not in the ECEMF template. This makes the comparison between the old and new campMapping quite hard to read.

## Purpose of this PR
Use ECEMF as  a basis and not NAVIGATE because this e.g. uses the national-reporting-corrected LULUCF values

# Checklist:
- [ ] I added an `x` in column `exclude_remind2_validation` for all `piam_variable` not produced by `remind2::convGDX2MIF` (for example EDGE-T, MAgPIE)
- [x ] I did not use Excel to open csv files or checked that no side-effects occur (changed values, many new quotation marks, …)

### CODE REVIEW

**Comment by orichters** [comment]
You can use `remind2::compareScenConf(fileList = c("oldfile.csv", "mappingfile.csv"), row.names = NULL)` to generate a human-readable comparison, see README.

**Comment by orichters** [comment]
I adjusted some minor things in NAVIGATE and CAMPAIGNers, you will have to adjust yours as well.

**Comment by jmuessel** [comment]
> Is CAMP really different from ECEMF, or can you just add some variables as we do [in ELEVATE](https://github.com/pik-piam/piamInterfaces/blob/master/inst/templates/mapping_template_ELEVATE.csv). The differences come from buildings, they have some new variables in there. @robinhasse can probably say more about this.

**Comment by orichters** [comment]
FYI: The mappings are now found at `inst/mappings/mapping_ECEMF.csv` because the whole package suffered from confusion what a template and a mapping is.

**Comment by orichters** [comment]
What is the status of this PR? We will have to adapt all mapping from US$2005 to 2017 soon and this might be easier when they are all collected here.

**Comment by jmuessel** [comment]
For transport I can say, that we don't need this template anymore - the project is already over. So maybe I take back this PR. @robinhasse what do you think about not having an official campaigners template? Idk if there are still issues with the template and would say, let's check for this only when we want the template to be part of the main branch.

**Comment by robinhasse** [comment]
> So maybe I take back this PR.

Fine, from my side.

**Comment by orichters** [comment]
Ok, fine, thanks!

**Pull request closed without merging**
