### PR TITLE
add and fix NAVIGATE summations

### LINKED ISSUE #332: variableInfo does not realize if variable is contained in multiple summation groups
So the `Final Energy 2` group is not recognized, see `piamInterfaces::variableInfo('Final Energy', mapping = 'AR6')`

```
##### Search for information on Final Energy in mappings

### Results from mapping: AR6
# Export variable groups found in summation_groups_AR6.csv          # Corresponding piam_variable variables
. Final Energy =                                                    . FE =
  + Final Energy|Electricity                                          + FE|+|Electricity
  + Final Energy|Gases                                                + FE|+|Gases
  + Final Energy|Heat                                                 + FE|+|Heat
  + Final Energy|Hydrogen                                             + FE|+|Hydrogen
  + Final Energy|Liquids                                              + FE|+|Liquids
  + Final Energy|Solids                                               + FE|+|Solids

# Child variables not in summation group
  . Final Energy|Residential and Commercial                           . FE|++|Buildings
  . Final Energy|Geothermal                                           . NA
  . Final Energy|Industry                                             . FE|++|Industry
  . Final Energy|Non-Energy Use                                       . NA
  . Final Energy|Other                                                . NA
  . Final Energy|Other Sector                                         . FE|++|CDR
  . Final Energy|Solar                                                . NA
  . Final Energy|Transportation                                       . FE|++|Transport
Units: EJ/yr                                                        Units: EJ/yr
```

### PR DESCRIPTION
**Pull request by orichters**
## Reviewers:
- @fbenke-pik: might you check just the code changes?

Might you please have a look only at those different parts of the [NAVIGATE mapping changes](https://github.com/pik-piam/piamInterfaces/pull/329/files#diff-831dafe67a14f466370eae61279d3b9a31a5283b5bce57b24551862bac837226)?
- @johannah-pik: 309, 890, 1080–1081
- @amerfort: few changes in the lines 108–248
- @robinhasse: lines 882–888
- @nicobauer: lines 713–751, 1258–1491

## Purpose of this PR

Code changes:
- in `checkSummations()`, be explicit what the % deviation means
- allow to have empty lines in `summation_group_*.csv` for structuring the file 
- avoid NA + NA + NA output in `variableInfo` similar to #327, and show also if the variable itself was found in the data (`keepparent`)
- add test that summation files don't contain duplicated lines which may mess up everything
- fixes #332 

Summation checks:
- add several summation checks to NAVIGATE template. I used the `mip::extractVariableGroups()` function on the variable list of the NAVIGATE template, and then manually separated the groups into plausible one, cross-checking with the `|+|` notation from remind2 when appropriate
- this leads to an overall 29 summation checks and I started to fix them
- add several variables that were missing, partly also introducing new NAVIGATE variables that were missing based on the [new community template](https://github.com/IAMconsortium/common-definitions). This means some variables will be missing for ELEVATE etc., but this is rather a mid-term investment.
- Adjust that all `Final Energy|Industry|*` variables use the `w/o Non-energy Use` in line with the variable description of the `Final Energy|Industry` main category, see [mattermost industry channel](https://mattermost.pik-potsdam.de/rd3/channels/industry-transformation/oc89q5biqpd3xgf1qx1mrp8oko)
- add Investment|Hydrogen|Electrolysis to the `Other` category, see https://github.com/pik-piam/piamInterfaces/issues/330
- add a hotfix for https://github.com/remindmodel/development_issues/issues/261 also regarding Gross Waste variables
- Now, only 13 failing summation checks remain from the transport sector. I agreed with the transport colleagues that they will have a look once the refactoring is done, hoping that many of these issues will be gone anyway.
- Here are summaries of the remaining issues as plots: [checkSummations_REMIND.pdf](https://github.com/user-attachments/files/16161768/checkSummations_REMIND.pdf)
- All the failing checks as data: [checkSummations.csv](https://github.com/user-attachments/files/16161770/checkSummations.csv)

The following overview is generated with:
```
devtools::load_all()
miff <- "/p/projects/remind/modeltests/remind/output/SSP2-NPi-AMT_2024-06-25_16.01.12/report.rds"
d <- piamInterfaces::generateIIASASubmission(miff, outputFilename = NULL, mapping = "NAVIGATE", checkSummation = FALSE)
checkSummations(d, summationsFile = "NAVIGATE", template = "NAVIGATE", generatePlots = TRUE, absDiff = 0.1, outputDirectory = "output")
```
Result:
- Note that https://github.com/pik-piam/piamInterfaces/issues/288, so some `+` might actually be a `-`
```
Emissions|CO2|Energy|Demand|Bunkers 2 <>                                      Emi|CO2|Energy|Demand|Transport|International Bunkers <>
   + Emissions|CO2|Energy|Demand|Bunkers|International Aviation                  + Emi|CO2|Transport|Pass|Aviation|International|Demand
   + Emissions|CO2|Energy|Demand|Bunkers|International Shipping                  + Emi|CO2|Transport|Freight|International Shipping|Demand
The child sum differs by -35.5% to 359% from the parent, absolute difference up to 288 Mt CO2/yr.

Emissions|CO2|Energy|Demand|Transportation 2 <>                               Emi|CO2|w/ Bunkers|Energy|Demand|Transport + Emi|CO2|Energy|Demand|Transport|International Bunkers <>
   + Emissions|CO2|Energy|Demand|Transportation|Bus                              + NA
   + Emissions|CO2|Energy|Demand|Transportation|Domestic Aviation                + NA
   + Emissions|CO2|Energy|Demand|Transportation|Domestic Shipping                + NA
   + Emissions|CO2|Energy|Demand|Transportation|LDV                              + Emi|CO2|Transport|Pass|Road|LDV|Demand
   + Emissions|CO2|Energy|Demand|Transportation|Rail                             + Emi|CO2|Transport|Rail|Demand
   + Emissions|CO2|Energy|Demand|Transportation|Truck                            + NA
The child sum differs by -86.1% to 16.8% from the parent, absolute difference up to 7134 Mt CO2/yr.
Variables not found in the data: Emissions|CO2|Energy|Demand|Transportation|Bus, Emissions|CO2|Energy|Demand|Transportation|Domestic Aviation, Emissions|CO2|Energy|Demand|Transportation|Domestic Shipping, Emissions|CO2|Energy|Demand|Transportation|Truck

Emissions|CO2|Energy|Demand|Transportation 3 <>                               Emi|CO2|w/ Bunkers|Energy|Demand|Transport + Emi|CO2|Energy|Demand|Transport|International Bunkers <>
   + Emissions|CO2|Energy|Demand|Transportation|Passenger                        + Emi|CO2|Transport|Pass|w/o bunkers|Demand
   + Emissions|CO2|Energy|Demand|Transportation|Freight                          + Emi|CO2|Transport|Freight|w/o bunkers|Demand
The child sum differs by -52.1% to 46.5% from the parent, absolute difference up to 727 Mt CO2/yr.

Emissions|CO2|Energy|Demand|Transportation|Passenger <>                       Emi|CO2|Transport|Pass|w/o bunkers|Demand <>
   + Emissions|CO2|Energy|Demand|Transportation|Passenger|Bus                    + Emi|CO2|Transport|Pass|Road|Bus|Demand
   + Emissions|CO2|Energy|Demand|Transportation|Passenger|Domestic Aviation      + Emi|CO2|Transport|Pass|Aviation|Domestic|Demand
   + Emissions|CO2|Energy|Demand|Transportation|Passenger|LDV                    + Emi|CO2|Transport|Pass|Road|LDV|Demand
   + Emissions|CO2|Energy|Demand|Transportation|Passenger|Rail                   + Emi|CO2|Transport|Pass|Rail|Demand
The child sum differs by -5.9% to 211% from the parent, absolute difference up to 375 Mt CO2/yr.

Energy Service|Transportation|Passenger <                                     ES|Transport|Pass|Road|Bus + ES|Transport|Pass|Road|LDV + ES|Transport|Pass|Rail + ES|Transport|Pass|Aviation|Domestic <
   + Energy Service|Transportation|Passenger|Domestic Aviation                   + ES|Transport|Pass|Aviation|Domestic
   + Energy Service|Transportation|Passenger|Domestic Navigation                 + NA
   + Energy Service|Transportation|Passenger|Other                               + NA
   + Energy Service|Transportation|Passenger|Railways                            + ES|Transport|Pass|Rail
   + Energy Service|Transportation|Passenger|Road                                + ES|Transport|Pass|Road
   + Energy Service|Transportation|Passenger|Cycling                             + ES|Transport|Pass|Road|Non-Motorized|Cycling
   + Energy Service|Transportation|Passenger|Walking                             + ES|Transport|Pass|Road|Non-Motorized|Walking
The child sum differs by 1.01% to 127% from the parent, absolute difference up to 15484 bn pkm/yr.
Variables not found in the data: Energy Service|Transportation|Passenger|Domestic Navigation, Energy Service|Transportation|Passenger|Other

Energy Service|Transportation|Passenger|Road <>                               ES|Transport|Pass|Road <>
   + Energy Service|Transportation|Passenger|Road|2W and 3W                      + ES|Transport|Pass|Road|LDV|Two Wheelers
   + Energy Service|Transportation|Passenger|Road|LDV                            + ES|Transport|Pass|Road|LDV
   + Energy Service|Transportation|Passenger|Road|Bus                            + ES|Transport|Pass|Road|Bus
The child sum differs by -33% to 31.1% from the parent, absolute difference up to 8548 bn pkm/yr.

Final Energy|Transportation (w/ bunkers) <                                    FE|Transport <
   + Final Energy|Transportation                                                 + FE|Transport|w/o Bunkers
   + Final Energy|Bunkers                                                        + FE|Transport|Pass|Aviation|International + FE|Transport|Freight|International Shipping
The child sum differs by 2.01% to 2.05% from the parent, absolute difference up to 0.337 EJ/yr.

Final Energy|Transportation 2 <>                                              FE|Transport|w/o Bunkers <>
   + Final Energy|Transportation|Bus                                             + FE|Transport|Pass|Road|Bus
   + Final Energy|Transportation|LDV                                             + FE|Transport|Pass|Road|LDV
   + Final Energy|Transportation|Rail                                            + FE|Transport|Rail
   + Final Energy|Transportation|Truck                                           + FE|Transport|Freight|Road
   + Final Energy|Transportation|Domestic Aviation                               + FE|Transport|Pass|Aviation|Domestic
   + Final Energy|Transportation|Domestic Shipping                               + FE|Transport|Freight|Navigation
The child sum differs by -15.5% to 42.5% from the parent, absolute difference up to 2.66 EJ/yr.

Final Energy|Transportation 3 <>                                              FE|Transport|w/o Bunkers <>
   + Final Energy|Transportation|Passenger                                       + FE|Transport|Pass|Pass|w/o Bunkers + FE|Transport|Pass|Road|Bus + FE|Transport|Pass|Road|LDV + FE|Transport|Pass|Rail + FE|Transport|Pass|Aviation|Domestic
   + Final Energy|Transportation|Freight                                         + FE|Transport|Freight|Road + FE|Transport|Freight|Rail + FE|Transport|Freight|Navigation
The child sum differs by -15.5% to 42.5% from the parent, absolute difference up to 2.66 EJ/yr.

Final Energy|Transportation|Freight <                                         FE|Transport|Freight|Road + FE|Transport|Freight|Rail + FE|Transport|Freight|Navigation <
   + Final Energy|Transportation|Freight|Electricity                             + FE|Transport|Freight|Electricity
   + Final Energy|Transportation|Freight|Gases                                   + FE|Transport|Freight|Gases
   + Final Energy|Transportation|Freight|Hydrogen                                + FE|Transport|Freight|Hydrogen
   + Final Energy|Transportation|Freight|Liquids                                 + FE|Transport|Freight|Liquids
   + Final Energy|Transportation|Freight|Other                                   + NA
The child sum differs by 5.59% to 112% from the parent, absolute difference up to 16 EJ/yr.
Variables not found in the data: Final Energy|Transportation|Freight|Other

Final Energy|Transportation|Freight|Liquids >                                 FE|Transport|Freight|Liquids >
   + Final Energy|Transportation|Freight|Liquids|Biomass                         + FE|Transport|Freight|Navigation|Liquids|Biomass + FE|Transport|Freight|Road|Liquids|Biomass + FE|Transport|Freight|Rail|Liquids|Biomass
   + Final Energy|Transportation|Freight|Liquids|Fossil                          + FE|Transport|Freight|Navigation|Liquids|Fossil + FE|Transport|Freight|Road|Liquids|Fossil + FE|Transport|Freight|Rail|Liquids|Fossil
   + Final Energy|Transportation|Freight|Liquids|Electricity                     + FE|Transport|Freight|Navigation|Liquids|Hydrogen + FE|Transport|Freight|Road|Liquids|Hydrogen + FE|Transport|Freight|Rail|Liquids|Hydrogen
The child sum differs by -54.6% to -6.11% from the parent, absolute difference up to 15.9 EJ/yr.

Final Energy|Transportation|LDV <>                                            FE|Transport|Pass|Road|LDV <>
   + Final Energy|Transportation|LDV|Electricity                                 + FE|Transport|LDV|Electricity
   + Final Energy|Transportation|LDV|Gases                                       + FE|Transport|LDV|Gases
   + Final Energy|Transportation|LDV|Hydrogen                                    + FE|Transport|LDV|Hydrogen
   + Final Energy|Transportation|LDV|Liquids                                     + FE|Transport|LDV|Liquids
The child sum differs by -28% to 64.9% from the parent, absolute difference up to 1.43 EJ/yr.

Final Energy|Transportation|Rail >                                            FE|Transport|Rail >
   + Final Energy|Transportation|Rail|Electricity                                + FE|Transport|Pass|Rail|Electricity + FE|Transport|Freight|Rail|Electricity
   + Final Energy|Transportation|Rail|Gases                                      + NA
   + Final Energy|Transportation|Rail|Hydrogen                                   + NA
   + Final Energy|Transportation|Rail|Liquids                                    + NA
The child sum differs by -95.4% to -20.6% from the parent, absolute difference up to 3.47 EJ/yr.
Variables not found in the data: Final Energy|Transportation|Rail|Gases, Final Energy|Transportation|Rail|Hydrogen, Final Energy|Transportation|Rail|Liquids
```

## Checklist:
- [x] I did not use Excel to open csv files or checked that no side-effects occur (changed values, many new quotation marks, …)
- [x] I added any renamed piam_variable to [`renamed_piam_variables.csv`](https://github.com/pik-piam/piamInterfaces/blob/master/inst/renamed_piam_variables.csv) to guarantee backwards compatibility.

It is recommended to have a look at the [tutorial](https://github.com/pik-piam/piamInterfaces/blob/master/tutorial.md) before submission.

### CODE REVIEW

**Comment by fbenke-pik** [comment]
Code changes look good to me.

**Review by jmuessel — APPROVED** [review]

**Review by robinhasse — APPROVED** [review]
I only looked at the buildings-related variables in `inst/mappings/mapping_NAVIGATE.csv` and they look good. Thanks, Oli!

**Review by amerfort — APPROVED** [review]
Thanks for taking care of this! lines 108–248 in the NAVIGATE mapping look ok

**Comment by nicobauer** [comment]
Checked and approved!

**Pull request merged**
