### PR TITLE
Adjustments in line with PR361 (Fix EDGE-T mapping issues)

### PR DESCRIPTION
**Pull request by laurinks**
## Purpose of this PR

Make adjustments in mapping_ScenarioMIP.csv to mirror changes made in PR #361 affecting `mapping_AR6.csv` and `mapping_NAVIGATE.csv`.

A few comments:
- AR6 variables "Final Energy|Transportation|Freight|Liquids|Oil" and "Energy Service|Transportation|Road" were not reported in ScenarioMIP
- piam_variable "FE|Transport|Pass|Road|LDV|Two-Wheelers" is _not_ included in ScenarioMIP
- Unit changes (bn->billion) implemented
- Several variables were not reported in earlier ScenarioMIP mapping due to difference in naming (ScenarioMIP template using "Light Duty Vehicle" while Navigate template using "LDV"). I manually added some of these (but still incomplete).

## Checklist:
- [x] I did not use Excel to open csv files or checked that no side-effects occur (changed values, many new quotation marks, …)
- [ ] I added any renamed piam_variable to [`renamed_piam_variables.csv`](https://github.com/pik-piam/piamInterfaces/blob/master/inst/renamed_piam_variables.csv) to guarantee backwards compatibility.

It is recommended to have a look at the [tutorial](https://github.com/pik-piam/piamInterfaces/blob/master/tutorial.md) before submission.

### CODE REVIEW

**Comment by laurinks** [comment]
@johannah-pik : I will take care of the failing checks (this has to do with me currently being unable to run `make build`). But it will not affect the mapping file.

**Comment by laurinks** [comment]
@orichters : I could finally make "make build" work on my local computer. At some point I was choosing "minor revision" which made the version number update. Is this okay/correct or should I have made a different choice? Overall, please let me know if something is wrong. It is the first time, so particularly happy to learn how to do the process right :)

**Review by orichters — APPROVED** [review]
Looks fine from my side, so seems like you mastered the process.

The `make build` process just makes sure the package can be actually used, and increasing the version number makes sure the new version is automatically installed on the cluster or when you update your R package. Whether that is a patch or a minor change is debatable, but also utterly irrelevant in my view. Of course, if you rewrite the whole package, you should not call it a patch.

**Comment by johannah-pik** [comment]
@laurinks looks good! I noticed two things when I checked the mapping: 
- FE\|Transport\|LDV\|Liquids should change to FE\|Transport\|Pass\|Road\|LDV\|Liquids
- FE\|Transport with bunkers should be replaced by FE|++|Transport

and do you meant that the Two Wheelers are **not** included?

**Comment by johannah-pik** [comment]
Could you replace `FE|Transport with bunkers` with `FE|++|Transport` in the NAVIGATE mapping as well?
Then I don't need to make a separate PR.
Thanks :)

**Comment by laurinks** [comment]
I made the changes for ScenarioMIP and NAVIGATE with the latest commit. Indeed, there was a "not" missing.

**Pull request merged**
