### PR TITLE
 automatically check piam_factor for 2005->2010 inflation correction & scale conversion

### PR DESCRIPTION
**Pull request by orichters**
## Purpose of this PR

To avoid errors such as in #215 that inflation corrections are somehow adjusted by strange Excel settings
- check that every conversion US$2005 -> US$2010 with everything else in the unit unchanged has a factor of 1.10774 (or -1.10774, if the variable name contains "Loss")
- also check that conversion from billion -> million, from Mt to kt and from GJ to MJ has a factor 1000 included etc.
- Add a factor = 1.10774 to some cases where the inflation conversion was missing (and factor was NA):
  - AR6:
    - Subsidies|Energy
    - Subsidies|Energy|Fossil
  - CAMPAIGNers and NAVIGATE:
    - Trade|Primary Energy|Biomass|Value
    - Trade|Primary Energy|Coal|Value
    - Trade|Primary Energy|Gas|Value
    - Trade|Primary Energy|Oil|Value
    - Trade|Uranium|Value
- Remove some `NA` from CAMPAIGNers, fix `EJ /yr` units by removing blanks.
- remove `Moving Avg` from `Price|Final Energy|Buildings|*` variables. The normal variable without `Moving Avg` is a Moving Avg anyway, but with some repairs and correct fixing on reference runs etc., see https://github.com/pik-piam/remind2/pull/402
- No idea why github shows that basically all lines have been touched in some of these files, maybe I changed the line endings or something stupid like that? Switch off whitespace changes and the diff is much more understandable: https://github.com/pik-piam/piamInterfaces/pull/221/files?diff=unified&w=1

## Checklist:
- [x] I added an `x` in column `exclude_remind2_validation` for all `piam_variable` not produced by `remind2::convGDX2MIF` (for example EDGE-T, MAgPIE)

### CODE REVIEW

**Review by fbenke-pik — APPROVED** [review]

**Comment by fbenke-pik** [comment]
Currently fails for CAMPAIGNers, so i guess this must wait until Jarusch has fixed the template.

**Comment by orichters** [comment]
-Maybe @robinhasse can have a look and confirm that the removal of `Moving Avg` is ok. If you need further explanation, let me know.
- Maybe @mleimbach can confirm that the Trade variables that have remind2 data in US$2005 must also be multiplied by 1.10774 to get US$2010 values

**Comment by mleimbach** [comment]
Conversion of prices is always tricky, but should in principle be the same for all variables. Using just an inflation rate is a short-cut that often is sufficient (also depends whether to convert prices in MER or PPP).

**Comment by mleimbach** [comment]
Price conversion is always tricky, but should in principle be the same for all variables. Using just the inflation rate is a short-cut which is often sufficient (also depends on whether prices are measured in PPP or MER).

**Pull request merged**
