### PR TITLE
Updating ECEMF variables and summations

### PR DESCRIPTION
**Pull request by Renato-Rodrigues**
- Adding capacity variables
- Fixing wrong variable mappings
- Adding summation groups

### CODE REVIEW

**Comment by Renato-Rodrigues** [comment]
I got an issue trying to run lucode2::buildLibrary().
@fbenke-pik @orichters Would any of you help me to figure out what is happening?

Error message:
```
── 4. Failure (test-generateIIASASubmission.R:27:7): test generateIIASASubmissio
`generateIIASASubmission(...)` threw an unexpected warning.
Message: Detected an unexpected many-to-many relationship between `x` and `y`.
i Row 559 of `x` matches multiple rows in `y`.
i Row 189 of `y` matches multiple rows in `x`.
i If a many-to-many relationship is expected, set `relationship = "many-to-many"` to silence this warning.
```

full buildLibrary output:
```
> library(lucode2)
> buildLibrary(autoCheckRepoUpToDate = FALSE)
Is your repo up-to-date? Did you pull from the upstreamrepo immediately before running this check? (Y/n) 
Y

ℹ Updating piamInterfaces documentation
ℹ Loading piamInterfaces
running linter in background, see C:\Users\renatoro\AppData\Local\Temp\RtmpiGDl6W\linter574439df3bdb.log
running tests in background, see C:\Users\renatoro\AppData\Local\Temp\RtmpiGDl6W\test57447678baa.log
Opening fd 1
══ Building ════════════════════════════════════════════════════════════════════
Setting env vars:
• CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
• CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
• CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX14FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX17FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX20FLAGS: -Wall -pedantic -fdiagnostics-color=always
── R CMD build ─────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\renatoro\Desktop\WIP\my_forks\piamInterfaces_ECEMF-variables-and-summations/DESCRIPTION' (339ms)
─  preparing 'piamInterfaces':
✔  checking DESCRIPTION meta-information ... 
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory 'piamInterfaces/mapping_template_ECEMF.csv'
─  building 'piamInterfaces_0.0.96.tar.gz'
   
══ Checking ════════════════════════════════════════════════════════════════════
Setting env vars:
• _R_CHECK_CRAN_INCOMING_REMOTE_               : FALSE
• _R_CHECK_CRAN_INCOMING_                      : FALSE
• _R_CHECK_FORCE_SUGGESTS_                     : FALSE
• _R_CHECK_PACKAGES_USED_IGNORE_UNUSED_IMPORTS_: FALSE
• NOT_CRAN                                     : true
• _R_CHECK_SYSTEM_CLOCK_                       : 0
── R CMD check ─────────────────────────────────────────────────────────────────
─  using log directory 'C:/Users/renatoro/AppData/Local/Temp/Rtmp6xIrdF/file4c5c39af417a/piamInterfaces.Rcheck' (420ms)
─  using R version 4.2.0 (2022-04-22 ucrt)
─  using platform: x86_64-w64-mingw32 (64-bit)
─  using session charset: UTF-8
─  using options '--no-tests --no-manual --as-cran'
✔  checking for file 'piamInterfaces/DESCRIPTION' ... 
─  checking extension type ... Package
─  this is package 'piamInterfaces' version '0.0.96'
─  package encoding: UTF-8
✔  checking package namespace information ... 
✔  checking package dependencies (3.5s)
✔  checking if this is a source package ... 
✔  checking if there is a namespace
✔  checking for executable files (1.1s)
✔  checking for hidden files and directories ... 
✔  checking for portable file names ... 
✔  checking serialization versions
✔  checking whether package 'piamInterfaces' can be installed (11.7s)
✔  checking installed package size ... 
✔  checking package directory (754ms)
✔  checking for future file timestamps ...
✔  checking DESCRIPTION meta-information (590ms)
✔  checking top-level files
✔  checking for left-over files ... 
✔  checking index information
✔  checking package subdirectories ... 
✔  checking R files for non-ASCII characters ... 
✔  checking R files for syntax errors ... 
✔  checking whether the package can be loaded (2.2s)
✔  checking whether the package can be loaded with stated dependencies (1.9s)
✔  checking whether the package can be unloaded cleanly (2s)
   checking whether the namespace can be loaded with stated dependencies ...

aborting due to test error:
ℹ Testing piamInterfaces
Starting 2 test processes
checkSummations: .............12.3......
checkDataLength: ..
plotIntercomparison: ..........
extractReferenceYear: .......
checkIIASASubmission: ...
generateMappingfile: ........................
getSummations: .........
getTemplate: ................................
loadIIASATemplate: ..
priceIndices: ......
reportWrongUnits: ......
summationsNames: ...
templateNames: .......
variableInfo: ........
generateIIASASubmission: ....W4.............

══ Warnings ════════════════════════════════════════════════════════════════════
1. test generateIIASASubmission with ECEMF (test-generateIIASASubmission.R:27:7) - Detected an unexpected many-to-many relationship between `x` and `y`.
i Row 103 of `x` matches multiple rows in `y`.
i Row 1765 of `y` matches multiple rows in `x`.
i If a many-to-many relationship is expected, set `relationship = "many-to-many"` to silence this warning.

══ Failed ══════════════════════════════════════════════════════════════════════
── 1. Failure (test-checkSummations.R:34:5): test summationFile without errors u
all(tmp$diff == 0) is not TRUE

`actual`:   <NA>
`expected`: TRUE

── 2. Failure (test-checkSummations.R:53:7): test summationFile with errors usin
`... <- NULL` did not throw the expected message.

── 3. Failure (test-checkSummations.R:59:5): test summationFile with errors usin
all(tmp$diff == 0) is not FALSE

`actual`:   <NA> 
`expected`: FALSE

── 4. Failure (test-generateIIASASubmission.R:27:7): test generateIIASASubmissio
`generateIIASASubmission(...)` threw an unexpected warning.
Message: Detected an unexpected many-to-many relationship between `x` and `y`.
i Row 559 of `x` matches multiple rows in `y`.
i Row 189 of `y` matches multiple rows in `x`.
i If a many-to-many relationship is expected, set `relationship = "many-to-many"` to silence this warning.
Class:   dplyr_warning_join_relationship_many_to_many/dplyr_warning_join/dplyr_warning/rlang_warning/warning/condition
Backtrace:
     ▆
  1. ├─testthat::expect_warning(...) at test-generateIIASASubmission.R:27:6
  2. │ └─testthat:::expect_condition_matching(...)
  3. │   └─testthat:::quasi_capture(...)
  4. │     ├─testthat (local) .capture(...)
  5. │     │ └─base::withCallingHandlers(...)
  6. │     └─rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo))
  7. ├─piamInterfaces::generateIIASASubmission(...)
  8. │ └─piamInterfaces::checkSummations(...) at piamInterfaces_ECEMF-variables-and-summations/R/generateIIASASubmission.R:123:4
  9. │   └─... %>% ... at piamInterfaces_ECEMF-variables-and-summations/R/checkSummations.R:46:2
 10. ├─dplyr::left_join(., summationGroups, by = c(variable = "child"))
 11. ├─dplyr:::left_join.data.frame(., summationGroups, by = c(variable = "child"))
 12. │ └─dplyr:::join_mutate(...)
 13. │   └─dplyr:::join_rows(...)
 14. │     └─dplyr:::dplyr_locate_matches(...)
 15. │       ├─base::withCallingHandlers(...)
 16. │       └─vctrs::vec_locate_matches(...)
 17. ├─vctrs:::warn_matches_relationship_many_to_many(...)
 18. │ └─vctrs:::warn_matches_relationship(...)
 19. │   └─vctrs:::warn_matches(...)
 20. │     └─vctrs:::warn_vctrs(...)
 21. │       └─rlang::warn(...)
 22. │         └─base::warning(cnd)
 23. │           └─base::withRestarts(...)
 24. │             └─base (local) withOneRestart(expr, restarts[[1L]])
 25. │               └─base (local) doWithOneRestart(return(expr), restart)
 26. └─dplyr (local) `<fn>`(`<vc______>`)
 27.   └─dplyr:::rethrow_warning_join_relationship_many_to_many(cnd, error_call)
 28.     └─dplyr:::warn_join(...)
 29.       └─dplyr:::warn_dplyr(...)

══ DONE ════════════════════════════════════════════════════════════════════════
Error : Test failures
Error in check(cran = cran, config = cfg) : lucode2::check failed

Restarting R session...

~/.Rprofile loaded!

> library(piamInterfaces)
Warning messages:
1: package ‘dplyr’ was built under R version 4.2.3 
2: package ‘lucode2’ was built under R version 4.2.3 
> buildLibrary(autoCheckRepoUpToDate = FALSE)
Is your repo up-to-date? Did you pull from the upstreamrepo immediately before running this check? (Y/n) 
Y

ℹ Updating piamInterfaces documentation
ℹ Loading piamInterfaces
running linter in background, see C:\Users\renatoro\AppData\Local\Temp\RtmpwzzYqe\linter4a78703f7f6f.log
running tests in background, see C:\Users\renatoro\AppData\Local\Temp\RtmpwzzYqe\test4a786e36215e.log
Opening fd 1
══ Building ════════════════════════════════════════════════════════════════════
Setting env vars:
• CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
• CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
• CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX14FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX17FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX20FLAGS: -Wall -pedantic -fdiagnostics-color=always
── R CMD build ─────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\renatoro\Desktop\WIP\my_forks\piamInterfaces_ECEMF-variables-and-summations/DESCRIPTION' (438ms)
─  preparing 'piamInterfaces':
✔  checking DESCRIPTION meta-information ... 
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory 'piamInterfaces/mapping_template_ECEMF.csv'
─  building 'piamInterfaces_0.0.96.tar.gz'
   
══ Checking ════════════════════════════════════════════════════════════════════
Setting env vars:
• _R_CHECK_CRAN_INCOMING_REMOTE_               : FALSE
• _R_CHECK_CRAN_INCOMING_                      : FALSE
• _R_CHECK_FORCE_SUGGESTS_                     : FALSE
• _R_CHECK_PACKAGES_USED_IGNORE_UNUSED_IMPORTS_: FALSE
• NOT_CRAN                                     : true
• _R_CHECK_SYSTEM_CLOCK_                       : 0
── R CMD check ─────────────────────────────────────────────────────────────────
─  using log directory 'C:/Users/renatoro/AppData/Local/Temp/Rtmp0sIirw/file56a8736365a6/piamInterfaces.Rcheck'
─  using R version 4.2.0 (2022-04-22 ucrt)
─  using platform: x86_64-w64-mingw32 (64-bit)
─  using session charset: UTF-8
─  using options '--no-tests --no-manual --as-cran'
✔  checking for file 'piamInterfaces/DESCRIPTION' ...
─  checking extension type ... Package
─  this is package 'piamInterfaces' version '0.0.96'
─  package encoding: UTF-8
✔  checking package namespace information ... 
✔  checking package dependencies (3.1s)
✔  checking if this is a source package ... 
✔  checking if there is a namespace
✔  checking for executable files (934ms)
✔  checking for hidden files and directories ... 
✔  checking for portable file names ... 
✔  checking serialization versions
✔  checking whether package 'piamInterfaces' can be installed (12.7s)
✔  checking installed package size ... 
✔  checking package directory (895ms)
✔  checking for future file timestamps ...
✔  checking DESCRIPTION meta-information (389ms)
✔  checking top-level files
✔  checking for left-over files ... 
✔  checking index information
✔  checking package subdirectories ... 
✔  checking R files for non-ASCII characters ... 
✔  checking R files for syntax errors ... 
✔  checking whether the package can be loaded (2.4s)
✔  checking whether the package can be loaded with stated dependencies (2.1s)
✔  checking whether the package can be unloaded cleanly (1.7s)
✔  checking whether the namespace can be loaded with stated dependencies (2s)
✔  checking whether the namespace can be unloaded cleanly (2.2s)
   checking loading without being on the library search path ...

aborting due to test error:
ℹ Testing piamInterfaces
Starting 2 test processes
checkSummations: .............12.3......
checkDataLength: ..
plotIntercomparison: ..........
extractReferenceYear: .......
checkIIASASubmission: ...
generateMappingfile: ........................
getSummations: .........
getTemplate: ................................
loadIIASATemplate: ..
priceIndices: ......
reportWrongUnits: ......
summationsNames: ...
templateNames: .......
variableInfo: ........
generateIIASASubmission: ....W4.............

══ Warnings ════════════════════════════════════════════════════════════════════
1. test generateIIASASubmission with ECEMF (test-generateIIASASubmission.R:27:7) - Detected an unexpected many-to-many relationship between `x` and `y`.
i Row 103 of `x` matches multiple rows in `y`.
i Row 1765 of `y` matches multiple rows in `x`.
i If a many-to-many relationship is expected, set `relationship = "many-to-many"` to silence this warning.

══ Failed ══════════════════════════════════════════════════════════════════════
── 1. Failure (test-checkSummations.R:34:5): test summationFile without errors u
all(tmp$diff == 0) is not TRUE

`actual`:   <NA>
`expected`: TRUE

── 2. Failure (test-checkSummations.R:53:7): test summationFile with errors usin
`... <- NULL` did not throw the expected message.

── 3. Failure (test-checkSummations.R:59:5): test summationFile with errors usin
all(tmp$diff == 0) is not FALSE

`actual`:   <NA> 
`expected`: FALSE

── 4. Failure (test-generateIIASASubmission.R:27:7): test generateIIASASubmissio
`generateIIASASubmission(...)` threw an unexpected warning.
Message: Detected an unexpected many-to-many relationship between `x` and `y`.
i Row 559 of `x` matches multiple rows in `y`.
i Row 189 of `y` matches multiple rows in `x`.
i If a many-to-many relationship is expected, set `relationship = "many-to-many"` to silence this warning.
Class:   dplyr_warning_join_relationship_many_to_many/dplyr_warning_join/dplyr_warning/rlang_warning/warning/condition
Backtrace:
     ▆
  1. ├─testthat::expect_warning(...) at test-generateIIASASubmission.R:27:6
  2. │ └─testthat:::expect_condition_matching(...)
  3. │   └─testthat:::quasi_capture(...)
  4. │     ├─testthat (local) .capture(...)
  5. │     │ └─base::withCallingHandlers(...)
  6. │     └─rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo))
  7. ├─piamInterfaces::generateIIASASubmission(...)
  8. │ └─piamInterfaces::checkSummations(...) at piamInterfaces_ECEMF-variables-and-summations/R/generateIIASASubmission.R:123:4
  9. │   └─... %>% ... at piamInterfaces_ECEMF-variables-and-summations/R/checkSummations.R:46:2
 10. ├─dplyr::left_join(., summationGroups, by = c(variable = "child"))
 11. ├─dplyr:::left_join.data.frame(., summationGroups, by = c(variable = "child"))
 12. │ └─dplyr:::join_mutate(...)
 13. │   └─dplyr:::join_rows(...)
 14. │     └─dplyr:::dplyr_locate_matches(...)
 15. │       ├─base::withCallingHandlers(...)
 16. │       └─vctrs::vec_locate_matches(...)
 17. ├─vctrs:::warn_matches_relationship_many_to_many(...)
 18. │ └─vctrs:::warn_matches_relationship(...)
 19. │   └─vctrs:::warn_matches(...)
 20. │     └─vctrs:::warn_vctrs(...)
 21. │       └─rlang::warn(...)
 22. │         └─base::warning(cnd)
 23. │           └─base::withRestarts(...)
 24. │             └─base (local) withOneRestart(expr, restarts[[1L]])
 25. │               └─base (local) doWithOneRestart(return(expr), restart)
 26. └─dplyr (local) `<fn>`(`<vc______>`)
 27.   └─dplyr:::rethrow_warning_join_relationship_many_to_many(cnd, error_call)
 28.     └─dplyr:::warn_join(...)
 29.       └─dplyr:::warn_dplyr(...)

══ DONE ════════════════════════════════════════════════════════════════════════
No one gets it right on their first try
Error : Test failures
Error in check(cran = cran, config = cfg) : lucode2::check failed
```

**Comment by orichters** [comment]
1. The "checkSummations" are errors because the tests are not cleverly set up, as ECEMF summation file does not contain [these variables](https://github.com/pik-piam/piamInterfaces/blob/master/tests/testthat/test-checkSummations.R#L2-L3). Maybe simply exclude "ECEMF" in [this line](https://github.com/pik-piam/piamInterfaces/blob/master/tests/testthat/test-checkSummations.R#L19C23-L19C44)

2. I have no time to investigate that now, but we had [similar problems before](https://github.com/pik-piam/piamInterfaces/pull/103). Maybe you find the "join" that causes it. Strange that it only shows up with ECEMF, not with AR6 etc.

**Review by orichters — APPROVED** [review]
Hey Renato, your errors in piamInterfaces are caused by two things: Your summation group is the first using the same child element multiple times, and that raises the dplyr error. And you have put [this specific `Final Energy|Industry` summation](https://github.com/pik-piam/piamInterfaces/blob/master/tests/testthat/test-checkSummations.R#L1) with the parent using `Final Energy|Industry 2` as intended, but this is broken at the moment until Falk merges [this PR](https://github.com/pik-piam/piamInterfaces/pull/141). I hope it is fine if Falk merges the stuff once he is back from holidays, you can go ahead and merge your PR if you like, your files are fine.

**Comment by Renato-Rodrigues** [comment]
Thank you for checking this @orichters!
I will hold my PR until Falk can take a look and we can find the best way to proceed. I can work in my local computer meanwhile.

**Comment by orichters** [comment]
Using your files, Falks PR with my latest adaption, I ran `make test` and it succeeds.

**Comment by fbenke-pik** [comment]
I merged my PR, but the test checkSummations still fails. This is because of [this line](https://github.com/pik-piam/piamInterfaces/blob/c52b7b3054d03a46b63e5bf272db5309442bcd5a/tests/testthat/test-checkSummations.R#L38). 

This is because the output of the summation check returns the summations using the variable `Final Energy|Industry 2` s in the summation file, but the test expects `Final Energy|Industry`. 

I think in this case the test should be adjusted to be more flexible. @orichters any ideas?

**Comment by orichters** [comment]
I'm fine with
```
    expect_true(any(grepl("^Final Energy\\|Industry( [0-9]+)?$", unique(tmp$variable))))
```

**Comment by fbenke-pik** [comment]
Sounds good. @Renato-Rodrigues can you adjust the code accordingly?

**Pull request merged**
