### PR TITLE
add automatic adjustment of 2005 to 2017 values

### PR DESCRIPTION
**Pull request by orichters**
## Purpose of this PR

- Prepare for MAgPIE and REMIND data being reporting in US$2017, but keep backwards compatibility
- Has to be done per variable, because some have MJ/US$2005 as a unit, and you have to divide by the factor
- Check whether the units in the data and the desired unit in the template only differ in that one is US$2005 and the other US$2017.
- If so, load the conversion factor, change the data and adapt the unit
- If I now change a mapping to US$2017, it also accepts US$2005 and US$05 as piam_unit, so we can change everything to the new values but the old one still work (but not inversely).
- If someone now comes with US$2010 or whatever, it will not work, but on the other hand that never worked.
- I suggest to adapt the piam_factors such that I multiply or divide (for 1/US$2005 units) the `piam_factor` by `convfact` as seen below, and then round to four significant numbers (is too much pseudo-precision?)
- I already added the values that the script below will generate to `R/checkUnitFactor.R`. Please, @Renato-Rodrigues, @fschreyer, @johanneskoch94, @fbenke-pik, whether that seems plausible to you:

```
# old:
1.12  US$2010     = 1 US$2005  # AR6, NAVIGATE
1.17  EUR_2020    = 1 US$2005  # ESABCC
1.174 EUR2020     = 1 US$2005  # ARIADNE
# from GDPuc:
1.231357 US$2017  = 1 US$2005
# new:
0.9096 US$2010    = 1 US$2017  # AR6, NAVIGATE
0.9502 EUR_2020   = 1 US$2017  # ESABCC
0.9534 EUR2020    = 1 US$2017  # ARIADNE
0.8121 USD05/tCO2 = 1 US$2017/tCO2
```

- [x] adjust the mappings using the following script:
```
library(tidyverse)
devtools::load_all()

convfact <- GDPuc::convertSingle(x = 1, iso3c = "USA", unit_in = "constant 2005 US$MER", unit_out = "constant 2017 US$MER")

for (n in seq_along(mappingNames())) {
as_tibble(getMapping(names(mappingNames())[[n]])) %>%
  mutate(piam_factor = as.numeric(piam_factor)) %>%
  mutate(piam_factor = ifelse(grepl("US$2005", piam_unit, fixed = TRUE) & is.finite(piam_factor), piam_factor / convfact, piam_factor)) %>%
  mutate(piam_factor = ifelse(grepl("/US$2005", piam_unit, fixed = TRUE) & is.finite(piam_factor), piam_factor * convfact * convfact, piam_factor)) %>%
  mutate(piam_factor = ifelse(is.finite(piam_factor), piamutils::niceround(piam_factor, 4), piam_factor)) %>%
  mutate(piam_unit = gsub("US$2005", "US$2017", piam_unit, fixed = TRUE)) %>%
  write.csv2(mappingNames()[[n]], na = "", row.names = FALSE, quote = FALSE)
}
```
- I had to add some `deletePlus` a bit earlier in the script to make sure the renaming, recalculation etc. works reliably.

## Reviewing the changes

Todo: check whether the adjustments of the piam_unit and the piam_factors make sense. Be particularly careful for variables where `piam_factor` is negative (CDR?; maybe search for `;-`) and where it there is a division by the unit (`EJ/US$2017`), because here you need to apply the inflation factor inversely.

I have just reviewer based on a first guess, please edit this text and assign someone else if needed.

- [x] code check (@fbenke-pik)
- [ ] mapping_AgMIP.csv (@FelicitasBeier)
- [x] mapping_AR6.csv (@orichters)
- [ ] mapping_AR6_MAgPIE.csv (@flohump)
- [x] mapping_AR6_NGFS.csv (@orichters)
- [ ] mapping_ARIADNE.csv (@fschreyer)
- [ ] mapping_ECEMF.csv (@Renato-Rodrigues)
- [x] mapping_ELEVATE.csv (@orichters)
- [ ] mapping_ESABCC.csv (@Renato-Rodrigues)
- [ ] mapping_NAVIGATE.csv (@strefler)
- [ ] mapping_SHAPE.csv (@bs538)
- [ ] mapping_ScenarioMIP.csv (@laurinks)

### CODE REVIEW

**Review by fbenke-pik — APPROVED** [review]

**Comment by orichters** [comment]
@LaviniaBaumstark asked me to merge this such that she can run further tests that require this version. Please check the mapping changes anyway.

**Comment by flohump** [comment]
> If someone now comes with US$2010 or US$05, it might not work, but this problem has to be checked for MAgPIE because they have lots of different units. But I think it's easier to tidy this up than to write a maximally flexible function.

To which template to you refer here specifically? To the AgMIP template?

**Comment by orichters** [comment]
> > If someone now comes with US$2010 or US$05, it might not work, but this problem has to be checked for MAgPIE because they have lots of different units. But I think it's easier to tidy this up than to write a maximally flexible function.
> 
> To which template to you refer here specifically? To the AgMIP template?

Both AgMIP and AR6_MAgPIE. But I actually just fixed that in [this commit](https://github.com/pik-piam/piamInterfaces/pull/299/commits/2e9a05695a42bef29ffb0d45afdd4c016a3d9aa0), so my old NGFS MAgPIE report.mif works without a problem.

**Comment by fschreyer** [comment]
Thanks, looks good. I guess, a comparison on AR6 level of e.g. investments / GDP before and after unit shift would be nice but I figure this is already under way.

**Comment by laurinks** [comment]
Thanks, ScenarioMIP looks good. I will come back to the question why there are so few variables affected in the Mattermost channel.

**Comment by strefler** [comment]
NAVIGATE mapping looks good to me, thanks

**Review by strefler — COMMENTED** [review]
NAVIGATE looks good

**Comment by FelicitasBeier** [comment]
For AgMIP, two lines have to be changed.
From: 
AWAG.AGR;USDMER05/h;Labor|Wages|Hourly labor costs;USDMER05/h;1;NULL;;M
AWAG.TOT;USDMER05/h;Labor|Wages|Hourly labor costs;USDMER05/h;1;NULL;;M
To:
AWAG.AGR;USD05/h;Labor|Wages|Hourly labor costs;US$2017/h;0.8121;NULL;;M
AWAG.TOT;USD05/h;Labor|Wages|Hourly labor costs;US$2017/h;0.8121;NULL;;M

I understood that you merged already, correct? Should I make a new PR with the fix?

**Pull request merged**
