### PR TITLE
adjust USD2005 to EUR2020 conversion in Ariadne template

### PR DESCRIPTION
**Pull request by fbenke-pik**
## Checklist:
- [x] I added an `x` in column `exclude_remind2_validation` for all `piam_variable` not produced by `remind2::convGDX2MIF` (for example EDGE-T, MAgPIE)
- [x] I did not use Excel to open csv files or checked that no side-effects occur (changed values, many new quotation marks, …)

### CODE REVIEW

**Comment by orichters** [comment]
@Renato-Rodrigues in ECEMF uses 1.17, you use 1.174. Is it not worth finding an agreement?

**Comment by fbenke-pik** [comment]
> @Renato-Rodrigues in ECEMF uses 1.17, you use 1.174. Is it not worth finding an agreement?

Not my field of expertise. The factor was given to me by Frederike and comes from Felix. So @fschreyer please respond to this.

**Comment by robertpietzcker** [comment]
> > @Renato-Rodrigues in ECEMF uses 1.17, you use 1.174. Is it not worth finding an agreement?

1.174 rounds to 1.17. 
so I would say it is fine if you use 1.174

**Comment by fbenke-pik** [comment]
Ok, merging for now. Please open a new issue if this needs further discussion.

**Pull request merged**
