### PR TITLE
Scenario mip update harmonization variables

### PR DESCRIPTION
**Pull request by merfort**
## Purpose of this PR
This PR updates the ScenarioMIP mapping
* adding some missing Emissions variables to the mapping template that were detected in [this issue](https://github.com/remindmodel/development_issues/issues/387), as well as some [variables that are needed for the harmonization process](https://docs.google.com/spreadsheets/d/1HKfl21NX8wohPEHpHlmf5XithknPw8zjLpVe4MiOU9U/edit?gid=1877841403#gid=1877841403)
* changing some variables in the mapping template to fix some summation check errors (in particular removing `Emi|N2O|+|Industry` from all `Emissions|N2O|Energy` categories, since these are process emissions)
* introducing a ScenarioMIP summation check template; all summation checks worked, apart form CO2, which is expected, since it needs some more clarification on the accounting of AFOLU emissions and CDR)

## Variables still missing after this PR
The following Emissions variables are still missing, but (most likely) only because we don't have them and/or they are already included in another sector.
 
### CO2
`Emissions|CO2|AFOLU|Agricultural Waste Burning`   -> we only have the total `Emi|CO2|+|Land-Use Change`
`Emissions|CO2|AFOLU|Land|Fires|Forest Burning`    -> we only have the total `Emi|CO2|+|Land-Use Change`
`Emissions|CO2|AFOLU|Land|Fires|Grassland Burning` -> we only have the total `Emi|CO2|+|Land-Use Change`
`Emissions|CO2|AFOLU|Land|Fires|Peat Burning`      -> we only have the total `Emi|CO2|+|Land-Use Change`
`Emissions|CO2|Product Use`                        -> we don't have that; is it implicitly part of something else?
`Emissions|CO2|Waste`                              -> is included in `Emissions|CO2|Energy|Supply`

### Gross CO2
`Gross Emissions|CO2|Energy|Supply|Other`          -> we don't have that

### BC
`Emissions|BC|Other`                               -> we don't have that
`Emissions|BC|Industrial Processes`                -> we don't have that
`Emissions|BC|Energy|Demand|Transportation|Domestic Aviation` -> is part of `Emissions|BC|Energy|Demand|Bunkers|International Aviation`
`Emissions|BC|Energy|Demand|Other Sector`          -> we don't have that
`Emissions|BC|AFOLU|Land|Fires|Peat Burning`       -> we don't have that

### C2F6
`Emissions|C2F6|AFOLU`                             -> we don't have that (only total `Emi|C2F6`)
`Emissions|C2F6|Energy`                            -> we don't have that (only total `Emi|C2F6`)
`Emissions|C2F6|Energy|Demand`                     -> we don't have that (only total `Emi|C2F6`)
`Emissions|C2F6|Energy|Supply`                     -> we don't have that (only total `Emi|C2F6`)
`Emissions|C2F6|Industrial Processes`              -> we don't have that (only total `Emi|C2F6`)

### CFC
`Emissions|CFC`                                    -> we don't have that

### CH4
`Emissions|CH4|Energy|Demand`                      -> we don't have that
`Emissions|CH4|Energy|Demand|Bunkers|International Shipping` -> we don't have that
`Emissions|CH4|Energy|Demand|Industry`             -> we don't have that
`Emissions|CH4|Energy|Demand|Other Sector`         -> we don't have that
`Emissions|CH4|Energy|Demand|Residential and Commercial and AFOFI` -> we don't have that
`Emissions|CH4|Energy|Demand|Transportation`       -> we don't have that
`Emissions|CH4|Industrial Processes`               -> we don't have that
`Emissions|CH4|Other`                              -> we don't have that
`Emissions|CH4|AFOLU|Land|Fires|Peat Burning`      -> we don't have that

### CO
`Emissions|CO|Energy|Demand|Transportation|Domestic Aviation` -> is part of `Emissions|CO|Energy|Demand|Bunkers|International Aviation`
`Emissions|CO|Energy|Demand|Other Sector`          -> we don't have that
`Emissions|CO|Industrial Processes`                -> we don't have that
`Emissions|CO|Other`                               -> we don't have that
`Emissions|CO|AFOLU|Land|Fires|Peat Burning`       -> we don't have that

### N2O
`Emissions|N2O|Energy|Demand|Bunkers|International Aviation` -> is included in `Emissions|N2O|Energy|Demand|Transportation`
`Emissions|N2O|Energy|Demand|Bunkers|International Shipping` -> is included in `Emissions|N2O|Energy|Demand|Transportation`
`Emissions|N2O|Energy|Demand|Transportation|Domestic Aviation` -> is included in `Emissions|N2O|Energy|Demand|Transportation`
`Emissions|N2O|Energy|Demand|Residential and Commercial and AFOFI` -> we don't have that
`Emissions|N2O|Energy|Demand|Other Sector`         -> we don't have that
`Emissions|N2O|Product Use`                        -> we don't have that
`Emissions|N2O|Other`                              -> we don't have that
`Emissions|N2O|AFOLU|Land|Fires|Peat Burning`      -> we don't have that

### NH3
`Emissions|NH3|Energy|Demand|Transportation|Domestic Aviation` -> is part of `Emissions|NH3|Energy|Demand|Bunkers|International Aviation`
`Emissions|NH3|Energy|Demand|Other Sector`         -> we don't have that
`Emissions|NH3|Industrial Processes`               -> we don't have that
`Emissions|NH3|Other`                              -> we don't have that
`Emissions|NH3|AFOLU|Land|Fires|Peat Burning`      -> we don't have that

### NOx
`Emissions|NOx|Energy|Demand|Transportation|Domestic Aviation` -> is part of `Emissions|NOx|Energy|Demand|Bunkers|International Aviation`
`Emissions|NOx|Energy|Demand|Other Sector`         -> we don't have that
`Emissions|NOx|Industrial Processes`               -> we don't have that
`Emissions|NOx|Other`                              -> we don't have that
`Emissions|NOx|AFOLU|Land|Fires|Peat Burning`      -> we don't have that

### OC
`Emissions|OC|Energy|Demand|Transportation|Domestic Aviation` -> is part of `Emissions|OC|Energy|Demand|Bunkers|International Aviation`
`Emissions|OC|Energy|Demand|Other Sector`         -> we don't have that
`Emissions|OC|Industrial Processes`               -> we don't have that
`Emissions|OC|Other`                              -> we don't have that
`Emissions|OC|AFOLU|Land|Fires|Peat Burning`      -> we don't have that

### Sulfur
`Emissions|Sulfur|Energy|Demand|Transportation|Domestic Aviation` -> is part of `Emissions|Sulfur|Energy|Demand|Bunkers|International Aviation`
`Emissions|Sulfur|Energy|Demand|Other Sector`         -> we don't have that
`Emissions|Sulfur|Industrial Processes`               -> we don't have that
`Emissions|Sulfur|Other`                              -> we don't have that
`Emissions|Sulfur|AFOLU|Land|Fires|Peat Burning`      -> we don't have that

### VOC
`Emissions|VOC|Energy|Demand|Transportation|Domestic Aviation` -> is part of `Emissions|VOC|Energy|Demand|Bunkers|International Aviation`
`Emissions|VOC|Energy|Demand|Other Sector`         -> we don't have that
`Emissions|VOC|Industrial Processes`               -> we don't have that
`Emissions|VOC|Other`                              -> we don't have that
`Emissions|VOC|AFOLU|Land|Fires|Peat Burning`      -> we don't have that

## Checklist:
- [x] I did not use Excel to open csv files or checked that no side-effects occur (changed values, many new quotation marks, …)
- [ ] I added any renamed piam_variable to [`renamed_piam_variables.csv`](https://github.com/pik-piam/piamInterfaces/blob/master/inst/renamed_piam_variables.csv) to guarantee backwards compatibility.

It is recommended to have a look at the [tutorial](https://github.com/pik-piam/piamInterfaces/blob/master/tutorial.md) before submission.

### CODE REVIEW

**Comment by laurinks** [comment]
Thanks a lot for the careful and rigorous work, @merfort ! Looks good to me.

**Review by laurinks — COMMENTED** [review]
Well spotted, @merfort ! As I wrote above, it looks good to me. Even though I had not seen the missing -1...

**Comment by gunnar-pik** [comment]
Thank you, Leon @merfort ! Looks also good to me. Again, the variables not reported by us are mostly sector-species combinations from the automated variable generation that are meaningless in the real world, because the respective species are not emitted from these sectors.

**Review by gunnar-pik — COMMENTED** [review]
Looks good!

**Comment by merfort** [comment]
Perfect, that was also my understanding. Thanks for the feedback!

**Pull request merged**
