### PR TITLE
fix double accounting of gases waste in secondary energy for ECEMF mappings

### PR DESCRIPTION
**Pull request by Renato-Rodrigues**

### CODE REVIEW

**Comment by orichters** [comment]
Hey @Renato-Rodrigues, can you please fix that in the other templates as well?

```
1. Test if REMIND reporting produces mandatory variables for Ariadne reporting ('test-piamInterfaces-Ariadne.R:24:5') - The following variables are expected in the piamInterfaces package,
          but cannot be found in the reporting generated:
 SE|Gases|+|Waste (EJ/yr)

2. Test if REMIND reporting produces mandatory variables for NAVIGATE reporting ('test-piamInterfaces-NAVIGATE.R:26:5') - The following variables are expected in the piamInterfaces package,
          but cannot be found in the reporting generated:
 SE|Gases|+|Waste (EJ/yr)

3. Test if REMIND reporting produces mandatory variables for NGFS reporting ('test-piamInterfaces-NGFS.R:28:5') - The following variables are expected in the piamInterfaces package,
          but cannot be found in the reporting generated:
 SE|Gases|+|Waste (EJ/yr)

4. Test if REMIND reporting produces mandatory variables for SHAPE reporting ('test-piamInterfaces-SHAPE.R:29:5') - The following variables are expected in the piamInterfaces package,
          but cannot be found in the reporting generated:
 SE|Gases|+|Waste (EJ/yr)
```

**Comment by Renato-Rodrigues** [comment]
this PR https://github.com/pik-piam/piamInterfaces/pull/165 contain the fixes for Ariadne and NAVIGATE and further explanation about the need to keep temporary support for this deprecated variable in the mappings.

There are no references of this variable in the NGFS and SHAPE templates, so I would assume that they are correct for now. Please let me know if I missed something.

**Comment by orichters** [comment]
The point is: you renamed it to `SE|Gases|Biomass|Waste` in remind2, but here it is still called `SE|Gases|+|Waste` and that need to be adjusted, I think.

**Comment by orichters** [comment]
Ok, sorry, I understand your point. We maybe need some "temporary rename" functionality to bridge such kind of renamings.

**Comment by Renato-Rodrigues** [comment]
> Ok, sorry, I understand your point. We maybe need some "temporary rename" functionality to bridge such kind of renamings.

Yeah, I am not 100% sure about the way to handle such cases. 
As this was caused by a mistake on the remind2 library, hopefully it shouldn't happen too often.
After discussing this with Falk, this "transition period" was the best compromise I could think to handle this.

**Pull request merged**
